def api_version() -> int: ...
def capabilities() -> list[str]: ...
def unpack_psp(data: bytes) -> bytes: ...
def pack_psb_object(obj: object, version: int, optimize: bool,
                    names: dict[str, int], strings: dict[str, int]) -> bytes: ...
def build_string_table(values: list[str], optimize: bool) -> tuple[list[int], bytes]: ...
